### PR TITLE
Added starpattern program

### PR DESCRIPTION
**Pull request by Sneha2319**

### CODE REVIEW

**Comment by spiderxp3** [comment]
Can you .md files instead of code because cookbook is like to cook codes with recipes. Make similar in other codes like their time complexity and visualization.

**Comment by Sneha2319** [comment]
Okay will Add it

**Comment by spiderxv** [comment]
Improve documentation with proper paragraphing and #(space) _title_

**Comment by spiderxv** [comment]
Also add some pics

**Pull request closed without merging**
