### PR TITLE
Added ArrayList.md

### PR DESCRIPTION
**Pull request by Sneha2319**

### CODE REVIEW

**Review by spiderxp3 — CHANGES_REQUESTED** [review]
Try to do like this in other PRs. This is gtg but improve working content and some pics also for deep explanation.

**Comment by Sneha2319** [comment]
Can you check it once done with changes.

**Comment by spiderxp3** [comment]
Yeah now good 👌👌 Happy hacking and best luck for open-source learning ✨

**Review by spiderxp3 — APPROVED** [review]

**Comment by Sneha2319** [comment]
Thanks , please look into other PRS also and let me  know if any changes  required!

**Pull request merged**
